### ISSUE TITLE
Support for interface defined beans

### ISSUE THREAD

**Issue by mira-silhavy** [antoinemeyer/mock-in-bean#13]
Hi,
I like your project, but I'm having some issues with it. 
E.g. I have an interface called `Service` and its implementation `ServiceImpl`. If I want to inject Mock or Spy into this bean but it doesn't work.
Could you make it work with interface defined beans. I think the problem is that `BeanUtils.findField` doesn't search for the field in actual bean instance but on interface.

```
java.lang.IllegalArgumentException: Cannot find bean to mock interface com.Processor in interface com.Service 
	at org.springframework.util.Assert.notNull(Assert.java:219)
	at com.teketik.test.mockinbean.MockInBeanTestContextManager$Context$Builder.processDefinitions(MockInBeanTestContextManager.java:125)
	at com.teketik.test.mockinbean.MockInBeanTestContextManager$Context$Builder.<init>(MockInBeanTestContextManager.java:109)
	at com.teketik.test.mockinbean.MockInBeanTestContextManager$Context$Builder.<init>(MockInBeanTestContextManager.java:90)
```

```
class Test {
    
    @Autowired
    private Service service;

    @SpyInBean(Service.class)
    private Processor processor;

...

**Comment by antoinemeyer** [comment]
Thanks.
I have added support for this usecase in `boot2-v1.4`.
Let me know if you face any issue
